#!/usr/bin/env bash
# Render .agents/mcp/servers.json (canonical) into each agent's native MCP config.
#
#   .agents/scripts/sync-mcp.sh         write .mcp.json, .cursor/mcp.json, .codex/config.toml
#   .agents/scripts/sync-mcp.sh check   change nothing; exit 1 if a generated file is stale
#
# servers.json maps a server name to one of:
#   {"type": "stdio", "command": "...", "args": ["..."], "env": {"KEY": "value"}}
#   {"type": "http", "url": "https://...", "headers": {"Name": "value"}}
# Anything else is rejected, so no agent silently gets a partial config.
#
# stdio servers always start in the repo root, so command and args may be repo-relative.
# Each agent spawns them from a different working directory, so the renderer wraps them in
# /bin/sh: Cursor gets `cd "${workspaceFolder}"`; Claude Code and Codex, which have no
# usable path variable, get `cd "$(git rev-parse --show-toplevel)"`. Codex reads
# .codex/config.toml only once the project is trusted. Requires jq (preinstalled on
# macOS 15+).
# shellcheck disable=SC2329 # the render_* functions are called indirectly, via write()
set -euo pipefail

AGENTS_DIR="$(cd "$(dirname "$0")/.." && pwd)"
REPO_ROOT="$(cd "$AGENTS_DIR/.." && pwd)"
SOURCE="$AGENTS_DIR/mcp/servers.json"
HEADER="Generated by .agents/scripts/sync-mcp.sh from .agents/mcp/servers.json. Do not edit."

command -v jq >/dev/null || { echo "sync-mcp: jq is required" >&2; exit 1; }

# Validate servers.json and give every server an explicit type.
normalized() {
    jq '
      def fail($m): error("servers.json: " + $m);
      def strmap: type == "object" and all(.[]; type == "string");
      if type != "object" then fail("top level must be an object of servers") else . end
      | with_entries(
          .key as $n
          | if (.value | type) != "object" then fail("\($n): must be an object") else . end
          | .value |= (
              .type = (.type // (if has("url") then "http" else "stdio" end))
              | .type as $t
              | if ($t != "stdio" and $t != "http") then fail("\($n): type must be stdio or http") else . end
              | (keys - (if $t == "stdio" then ["type", "command", "args", "env"] else ["type", "url", "headers"] end)) as $extra
              | if ($extra | length) > 0
                then fail("\($n): unsupported field(s) for \($t): \($extra | join(", ")); extend sync-mcp.sh")
                else . end
              | if $t == "stdio" and (.command | type) != "string" then fail("\($n): stdio needs a command string") else . end
              | if $t == "http" and (.url | type) != "string" then fail("\($n): http needs a url string") else . end
              | if has("args") and ((.args | type) != "array" or any(.args[]; type != "string"))
                then fail("\($n): args must be an array of strings") else . end
              | if has("env") and (.env | strmap | not) then fail("\($n): env must map names to strings") else . end
              | if has("headers") and (.headers | strmap | not) then fail("\($n): headers must map names to strings") else . end
              | if any(.. | strings; test("\\$[{(]"))
                then fail("\($n): ${...} and $(...) are not supported; each agent expands them differently")
                else . end
            )
        )
    ' "$SOURCE"
}

# jq helpers: `from_root($root)` turns a stdio server into a /bin/sh launcher that first
# changes into the repo root. Every word is single-quoted for the shell; jq gets the quote
# character as $q (--arg q "'"). The $(...) below is meant literally.
# shellcheck disable=SC2016
JQ_LIB='
  def shq: $q + gsub($q; $q + "\\" + $q + $q) + $q;
  def from_root($root):
    {command: "/bin/sh",
     args: ["-c", "cd \"\($root)\" && exec " + ([.command] + (.args // []) | map(shq) | join(" "))]}
    + (if has("env") then {env} else {} end);
  def git_root: "$(git rev-parse --show-toplevel)";
'

render_claude() { # Claude Code wants an explicit "type" for every server.
    jq --arg q "'" "$JQ_LIB"'
      {mcpServers: map_values(if .type == "stdio" then {type: "stdio"} + from_root(git_root) else . end)}'
}

render_cursor() { # Cursor documents "type" as required for stdio; its URL examples omit it.
    jq --arg q "'" "$JQ_LIB"'
      {mcpServers: map_values(
        if .type == "stdio" then {type: "stdio"} + from_root("${workspaceFolder}") else del(.type) end)}'
}

render_codex() { # Codex infers the transport; static HTTP headers are "http_headers".
    echo "# $HEADER"
    jq -r --arg q "'" "$JQ_LIB"'
      def tkey: if test("^[A-Za-z0-9_-]+$") then . else tojson end;
      def tval:  # JSON string escapes are also valid TOML basic-string escapes
        if type == "array" then "[" + (map(tval) | join(", ")) + "]"
        elif type == "object" then "{ " + (to_entries | map("\(.key | tkey) = \(.value | tval)") | join(", ")) + " }"
        else tojson end;
      to_entries[]
      | .key as $n
      | (.value | if .type == "stdio" then from_root(git_root) else . end) as $s
      | (if $s.command
         then [["command", $s.command], ["args", $s.args], ["env", $s.env]]
         else [["url", $s.url], ["http_headers", $s.headers]] end)
      | map(select(.[1] != null) | "\(.[0]) = \(.[1] | tval)")
      | "\n[mcp_servers.\($n | tkey)]\n" + join("\n")'
}

# write <relative path> <renderer>: render into the file, or compare in check mode.
stale=0
write() {
    local rel="$1" renderer="$2" tmp
    tmp="$(mktemp)"
    normalized | "$renderer" >"$tmp"
    if [ "$MODE" = check ]; then
        if ! cmp -s "$tmp" "$REPO_ROOT/$rel"; then
            echo "sync-mcp: $rel is stale (run .agents/scripts/sync-mcp.sh)" >&2
            stale=1
        fi
        rm -f "$tmp"
    else
        mkdir -p "$(dirname "$REPO_ROOT/$rel")"
        mv "$tmp" "$REPO_ROOT/$rel"
        echo "Wrote: $rel"
    fi
}

MODE="${1:-apply}"
case "$MODE" in
    apply | check) ;;
    *) echo "usage: $0 [check]" >&2; exit 2 ;;
esac
write .mcp.json render_claude
write .cursor/mcp.json render_cursor
write .codex/config.toml render_codex
exit "$stale"
