"""Publish fixture excerpts and the tested SDK example to the static website.

Run from any directory. --check detects stale generated files without modifying them.
Never exports fixture live flags, addresses, hashes or fabricated transaction links.
"""
import argparse
import html
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def artifacts():
    cases = {c["case_id"]: c for c in json.loads((ROOT / "dashboard/fixtures/cases.json").read_text())}
    scenarios = json.loads((ROOT / "dashboard/fixtures/website-scenarios.json").read_text())
    for scenario in scenarios:
        case = cases[scenario.pop("case_id")]
        scenario.update(verdict=case["verdict"], headline=case["headline"])
        scenario["checks"] = [{k: c[k] for k in ("name", "status", "summary")} for c in case["checks"] if c["name"] != "intercepta.deep_scan"]
        scenario["reasons"] = [{k: r[k] for k in ("rule", "label", "detail")} for r in case["reasons"]]
    data = "// Generated by scripts/build_website_demo.py; synthetic fixtures only.\n"
    data += "export const scenarios = " + json.dumps(scenarios, ensure_ascii=False, indent=2) + ";\n"
    example = (ROOT / "sdk/examples/screen_before_signing.py").read_text()
    snippet = "from sekisho import SekishoClient, SekishoError\n\n" + example.split("# website-example:start\n")[1].split("# website-example:end")[0].rstrip()
    page = (ROOT / "website/index.html").read_text()
    before, rest = page.split("<!-- sdk-example:start -->")
    _, after = rest.split("<!-- sdk-example:end -->")
    page = before + '<!-- sdk-example:start --><pre tabindex="0" aria-label="Python SDK example"><code id="sdk-code">' + html.escape(snippet) + '</code></pre><!-- sdk-example:end -->' + after
    return {"website/demo-data.mjs": data, "website/screen_before_signing.py": example, "website/index.html": page}


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    stale = []
    for name, content in artifacts().items():
        path = ROOT / name
        if args.check:
            if not path.exists() or path.read_text() != content:
                stale.append(name)
        else:
            path.write_text(content)
    if stale:
        raise SystemExit("Stale website artifacts: " + ", ".join(stale))
    print("Website fixture excerpts and SDK example are current.")
