// Generated by scripts/build_website_demo.py; synthetic fixtures only.
export const scenarios = [
  {
    "id": "clean",
    "label": "Clean wallet",
    "outcome": "The agent may proceed to signing under this example policy. ALLOW is a point-in-time verdict, not a guarantee of safety or settlement.",
    "verdict": "ALLOW",
    "headline": "No policy rule triggered",
    "checks": [
      {
        "name": "intercepta.quick_scan",
        "status": "ok",
        "summary": "toxicScore 0, no traits"
      },
      {
        "name": "sanctions.oracle",
        "status": "ok",
        "summary": "not sanctioned on 1, 8453"
      },
      {
        "name": "trace.source_of_funds",
        "status": "ok",
        "summary": "no inbound history"
      },
      {
        "name": "intercepta.impersonation",
        "status": "ok",
        "summary": "not poisoned"
      },
      {
        "name": "intercepta.token",
        "status": "ok",
        "summary": "USDC (Base): action info, risk 0"
      }
    ],
    "reasons": []
  },
  {
    "id": "mixer",
    "label": "Mixer exposure",
    "outcome": "In this example, the buyer deposits 0.05 USDC into escrow instead of paying the vendor. An officer reviews the evidence before release or refund. Mixer exposure is not the same as sanctions.",
    "verdict": "HOLD",
    "headline": "Counterparty has mixer exposure",
    "checks": [
      {
        "name": "intercepta.quick_scan",
        "status": "ok",
        "summary": "toxicScore 58, 2 traits"
      },
      {
        "name": "sanctions.oracle",
        "status": "ok",
        "summary": "not sanctioned on 1, 8453"
      },
      {
        "name": "trace.source_of_funds",
        "status": "ok",
        "summary": "taint 21.2%, 5 funders, 1 flagged"
      },
      {
        "name": "intercepta.impersonation",
        "status": "ok",
        "summary": "not poisoned"
      },
      {
        "name": "intercepta.token",
        "status": "ok",
        "summary": "USDC (Base): action info, risk 0"
      }
    ],
    "reasons": [
      {
        "rule": "hold_trait:mixer_transfers",
        "label": "mixer_transfers",
        "detail": "The address has sent or received funds through a mixer service."
      },
      {
        "rule": "toxic_score_hold",
        "label": "Intercepta toxicScore at or above the hold threshold",
        "detail": "toxicScore 58 ≥ 40"
      },
      {
        "rule": "taint_hold",
        "label": "Source of funds: taint",
        "detail": "taint 21.2% of traced inbound value from flagged sources (threshold 10%); Tornado Cash: Router → counterparty (Ethereum, $715); Tornado Cash: 10 ETH → 0xCF4e…Ecb9 → counterparty (Ethereum, $200)"
      }
    ]
  },
  {
    "id": "sanctioned",
    "label": "Sanctioned wallet",
    "outcome": "The agent refuses the payment. No payment signature is created. The blocked decision can still be recorded for audit.",
    "verdict": "BLOCK",
    "headline": "Counterparty is on a sanctions list",
    "checks": [
      {
        "name": "intercepta.quick_scan",
        "status": "ok",
        "summary": "toxicScore 92, 2 traits"
      },
      {
        "name": "sanctions.oracle",
        "status": "ok",
        "summary": "sanctioned on 1"
      },
      {
        "name": "trace.source_of_funds",
        "status": "ok",
        "summary": "taint 96.4%, 3 funders, 1 flagged"
      },
      {
        "name": "intercepta.impersonation",
        "status": "ok",
        "summary": "not poisoned"
      },
      {
        "name": "intercepta.token",
        "status": "ok",
        "summary": "USDC (Base): action info, risk 0"
      }
    ],
    "reasons": [
      {
        "rule": "sanctions_oracle",
        "label": "Sanctioned address (onchain oracle)",
        "detail": "isSanctioned = true on Ethereum"
      },
      {
        "rule": "toxic_score_block",
        "label": "Intercepta toxicScore at or above the block threshold",
        "detail": "toxicScore 92 ≥ 80"
      },
      {
        "rule": "taint_block",
        "label": "Source of funds: high taint",
        "detail": "taint 96.4% of traced inbound value from flagged sources (threshold 50%); Ronin Bridge Exploiter → counterparty (Ethereum, $1,250,000)"
      },
      {
        "rule": "hold_trait:sanction_address_communication",
        "label": "sanction_address_communication",
        "detail": "The address has interacted with addresses that are included in sanctions lists."
      },
      {
        "rule": "toxic_score_hold",
        "label": "Intercepta toxicScore at or above the hold threshold",
        "detail": "toxicScore 92 ≥ 40"
      },
      {
        "rule": "taint_hold",
        "label": "Source of funds: taint",
        "detail": "taint 96.4% of traced inbound value from flagged sources (threshold 10%); Ronin Bridge Exploiter → counterparty (Ethereum, $1,250,000)"
      }
    ]
  },
  {
    "id": "unavailable",
    "label": "Screening timeout",
    "outcome": "Missing screening data cannot produce ALLOW. Pause payment and investigate or retry screening. A passing sanctions check alone is insufficient.",
    "verdict": "HOLD",
    "headline": "Screening unavailable, payment held",
    "checks": [
      {
        "name": "intercepta.quick_scan",
        "status": "error",
        "summary": "timed out after 3,000 ms"
      },
      {
        "name": "sanctions.oracle",
        "status": "ok",
        "summary": "not sanctioned on 1, 8453"
      },
      {
        "name": "trace.source_of_funds",
        "status": "ok",
        "summary": "taint 0%, 4 funders (cached)"
      },
      {
        "name": "intercepta.impersonation",
        "status": "error",
        "summary": "timed out after 3,000 ms"
      },
      {
        "name": "intercepta.token",
        "status": "ok",
        "summary": "USDC (Base): action info, risk 0"
      }
    ],
    "reasons": [
      {
        "rule": "screening_error",
        "label": "Screening unavailable (fail closed)",
        "detail": "Intercepta Quick Scan error: timed out after 3,000 ms. Policy fails closed: never ALLOW on missing data."
      }
    ]
  }
];
